language: node_js
node_js:
- node
- '8'
before_install:
- npm install -g coveralls
script:
- npm run build
- npm run lint
- npm run test
sudo: false
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- npm run coverage:report
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:docs; fi
before_deploy:
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    npm version "$(npm view currency.js@latest version)-${TRAVIS_COMMIT:0:8}";
  fi
deploy:
- provider: npm
  skip_cleanup: true
  on:
    tags: true
    node: node
- provider: npm
  skip_cleanup: true
  on:
    branch: master
    node: node
  tag: next
- provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: docs/build
  on:
    branch: master
    node: node
