language: node_js
node_js:
- node
- '8'
before_install:
- npm install -g coveralls
script:
- npm run build
- npm run lint
- npm run test
sudo: false
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- npm run coverage:report
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:docs; fi
before_deploy:
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    npm version "$(npm view currency.js@latest version)-${TRAVIS_COMMIT:0:8}";
  fi
deploy:
- provider: npm
  skip_cleanup: true
  email:
    secure: E5X6CQNG5Qj32TVZv6OJRFtaXZKSBd9fR/u20yWZik1BCpGNzQ9A42+xXkjliHWwu7n2Xh482iaqgiv00NWVzPMaycFVJrF7SPHDl08SH6p/R5DvgLQV79ISBtEwHxzDC3hrJOeVFknZMKaGo+TUQXiL7CYVnHMxHqlTDNJKh6g=
  on:
    tags: true
    node: node
- provider: npm
  skip_cleanup: true
  email:
    secure: E5X6CQNG5Qj32TVZv6OJRFtaXZKSBd9fR/u20yWZik1BCpGNzQ9A42+xXkjliHWwu7n2Xh482iaqgiv00NWVzPMaycFVJrF7SPHDl08SH6p/R5DvgLQV79ISBtEwHxzDC3hrJOeVFknZMKaGo+TUQXiL7CYVnHMxHqlTDNJKh6g=
  on:
    branch: master
    node: node
  tag: next
- provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: docs/build
  on:
    branch: master
    node: node
